@php
 $services=config('touch2finish.services',[]); $quoteForm=config('touch2finish.quote_form');
 $queryService=request()->query('service'); $validQuery=array_key_exists($queryService,$services)||$queryService===$quoteForm['combined_slug']; $selectedService=old('service',$validQuery?$queryService:'');
 $inputClass=fn($field)=>'t2f-input '.($errors->has($field)?'error':'');
 $detailFields=collect($quoteForm['detail_fields']??[])->flatten()->push('combined_services.*')->all();
 $hasDetailErrors=$errors->hasAny($detailFields);
 $hasOldDetails=collect($detailFields)->contains(fn($field)=>$field!=='combined_services.*'&&filled(old($field)));
 $openDetails=$selectedService!==''&&($validQuery||$hasDetailErrors||$hasOldDetails||old('service'));
@endphp
<div class="quote-form-shell" x-data="{ submitting:false, service:@js($selectedService), detailsOpen:@js((bool) $openDetails), files:[], updateFiles(e){this.files=Array.from(e.target.files)}, removeFile(i){const d=new DataTransfer();this.files.filter((_,n)=>n!==i).forEach(f=>d.items.add(f));this.$refs.photos.files=d.files;this.files=Array.from(d.files)} }" x-effect="if (!service) detailsOpen=false">
 <div class="mb-7"><h3 class="font-display text-2xl font-bold text-touch-dark">Request your free quotation</h3><p class="mt-2 text-sm leading-6 text-touch-muted">Fields marked &ldquo;required&rdquo; must be completed.</p></div>
 @if($errors->any())<div class="mb-6 rounded-md border border-red-200 bg-red-50 p-4" role="alert"><p class="font-semibold text-red-800">Please correct the following:</p><ul class="mt-2 list-disc space-y-1 pl-5 text-sm text-red-700">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul><p class="mt-3 text-sm text-red-700">Any photographs must be selected again.</p></div>@endif
 <form action="{{ route('quote.submit') }}" method="POST" enctype="multipart/form-data" @submit="submitting=true" class="space-y-8" novalidate>@csrf
  <div class="absolute -left-[10000px] h-px w-px overflow-hidden" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" type="text" tabindex="-1" autocomplete="off"></div>
  <fieldset><legend class="mb-4 font-display text-lg font-bold text-touch-dark">1. Contact Information</legend><div class="grid gap-5 sm:grid-cols-2">
   @foreach([['name','Full name','text','name'],['email','Email address','email','email'],['phone','Phone number','tel','tel'],['postcode','Postcode','text','postal-code']] as [$field,$label,$type,$autocomplete])<div><label for="{{ $field }}" class="form-label">{{ $label }} (required)</label><input id="{{ $field }}" name="{{ $field }}" type="{{ $type }}" value="{{ old($field) }}" autocomplete="{{ $autocomplete }}" class="{{ $inputClass($field) }}" @error($field) aria-invalid="true" aria-describedby="{{ $field }}-error" @enderror>@error($field)<p id="{{ $field }}-error" class="form-error">{{ $message }}</p>@enderror</div>@endforeach
  </div></fieldset>
  <fieldset class="border-t border-touch-border pt-7"><legend class="mb-4 font-display text-lg font-bold text-touch-dark">2. Service Required</legend>
   <label for="service" class="form-label">Service (required)</label><select id="service" name="service" x-model="service" class="{{ $inputClass('service') }}" @error('service') aria-invalid="true" aria-describedby="service-error" @enderror><option value="">Select a service</option>@foreach($services as $slug=>$item)<option value="{{ $slug }}" @selected($selectedService===$slug)>{{ $item['title'] }}</option>@endforeach<option value="combined-services" @selected($selectedService==='combined-services')>{{ $quoteForm['combined_title'] }}</option></select>@error('service')<p id="service-error" class="form-error">{{ $message }}</p>@enderror
   <div class="mt-5 grid gap-5 sm:grid-cols-2"><div><label for="preferred_date" class="form-label">Preferred date</label><input id="preferred_date" name="preferred_date" type="date" min="{{ now()->toDateString() }}" value="{{ old('preferred_date') }}" class="{{ $inputClass('preferred_date') }}">@error('preferred_date')<p class="form-error">{{ $message }}</p>@enderror</div>
   <fieldset><legend class="form-label">Preferred contact method (required)</legend><div class="flex flex-wrap gap-4 pt-2">@foreach($quoteForm['preferred_contact_methods'] as $value=>$label)<label class="inline-flex items-center gap-2 text-sm"><input type="radio" name="preferred_contact_method" value="{{ $value }}" @checked(old('preferred_contact_method')===$value)> {{ $label }}</label>@endforeach</div>@error('preferred_contact_method')<p class="form-error">{{ $message }}</p>@enderror</fieldset></div>
  </fieldset>
   <div class="border-t border-touch-border pt-7" x-show="service" x-cloak>
    <button type="button" class="flex w-full items-center justify-between gap-4 rounded-md text-left" @click="detailsOpen=!detailsOpen" :aria-expanded="detailsOpen.toString()" aria-controls="additional-service-details"><span><span class="block font-display text-lg font-bold text-touch-dark">Add more service details</span><span class="mt-1 block text-sm text-touch-muted">Optional</span></span><i data-lucide="chevron-down" class="h-5 w-5 shrink-0 text-touch-dark transition-transform" :class="detailsOpen ? 'rotate-180' : ''" aria-hidden="true"></i></button>
    <div id="additional-service-details" x-show="detailsOpen" x-cloak class="mt-6">
   <div x-show="service==='mobile-car-valeting'" x-transition.opacity.duration.200ms class="grid gap-5 sm:grid-cols-2"><x-site.quote-input name="vehicle_make_model" label="Vehicle make and model" />@foreach(['vehicle_size'=>'Vehicle size','vehicle_condition'=>'Current vehicle condition','water_available'=>'Is water available at the service location?','electricity_available'=>'Is electricity available at the service location?'] as $field=>$label)<x-site.quote-select :name="$field" :label="$label" :options="$quoteForm['options'][in_array($field,['water_available','electricity_available'])?'availability':$field]" />@endforeach</div>
   <div x-show="service==='domestic-commercial-cleaning'" x-transition.opacity.duration.200ms class="grid gap-5 sm:grid-cols-2"><x-site.quote-select name="property_type" label="Property type" :options="$quoteForm['options']['property_type']" /><x-site.quote-input name="bedrooms" label="Number of bedrooms" type="number" /><x-site.quote-input name="bathrooms" label="Number of bathrooms" type="number" /><x-site.quote-select name="cleaning_type" label="Type of cleaning required" :options="$quoteForm['options']['cleaning_type']" /><x-site.quote-select name="occupancy_status" label="Property status" :options="$quoteForm['options']['occupancy_status']" /></div>
   <div x-show="service==='removals-man-and-van'" x-transition.opacity.duration.200ms class="grid gap-5 sm:grid-cols-2"><x-site.quote-input name="collection_postcode" label="Collection postcode" /><x-site.quote-input name="delivery_postcode" label="Delivery postcode" /><x-site.quote-select name="property_size" label="Property or move size" :options="$quoteForm['options']['property_size']" /><x-site.quote-input name="floor_level" label="Floor or access information" /><x-site.quote-select name="lift_available" label="Is a lift available where required?" :options="$quoteForm['options']['lift_available']" /><x-site.quote-input name="moving_date" label="Preferred moving date" type="date" /><x-site.quote-textarea name="large_items" label="Large, heavy or fragile items" placeholder="List any wardrobes, appliances, pianos, large furniture, fragile items or other important belongings." /></div>
   <div x-show="service==='handyman-property-maintenance'" x-transition.opacity.duration.200ms class="space-y-5"><x-site.quote-textarea name="task_list" label="Complete task list" placeholder="List every task you would like the team to review." /><x-site.quote-select name="materials_available" label="Are the required materials already available?" :options="$quoteForm['options']['materials_available']" /><p class="text-sm leading-6 text-touch-muted">Regulated gas, electrical, structural or specialist work must be reviewed separately and may require an appropriately qualified professional.</p></div>
   <div x-show="service==='refurbishment-decorating'" x-transition.opacity.duration.200ms class="grid gap-5 sm:grid-cols-2"><x-site.quote-input name="number_of_rooms" label="Number of rooms or areas" type="number" /><x-site.quote-select name="property_status" label="Property status" :options="$quoteForm['options']['property_status']" /><x-site.quote-select name="surface_condition" label="Current surface condition" :options="$quoteForm['options']['surface_condition']" /><x-site.quote-textarea name="desired_finish" label="Describe the intended finish" placeholder="Describe the colours, paint, wallpaper, repairs or result you want to achieve." /></div>
   <div x-show="service==='combined-services'" x-transition.opacity.duration.200ms class="space-y-5"><fieldset><legend class="form-label">Services required</legend><div class="grid gap-2 sm:grid-cols-2">@foreach($services as $slug=>$item)<label class="flex items-start gap-2 text-sm"><input type="checkbox" name="combined_services[]" value="{{ $slug }}" @checked(in_array($slug,old('combined_services',[])))> {{ $item['title'] }}</label>@endforeach</div></fieldset><x-site.quote-textarea name="combined_details" label="How should the services work together?" /></div>
    </div>
   </div>
   <fieldset class="border-t border-touch-border pt-7"><legend class="mb-4 font-display text-lg font-bold text-touch-dark">3. Project Description</legend><label for="message" class="form-label">Project or service details (required)</label><textarea id="message" name="message" rows="6" class="{{ $inputClass('message') }} resize-y" @error('message') aria-invalid="true" @enderror>{{ old('message') }}</textarea>@error('message')<p class="form-error">{{ $message }}</p>@enderror</fieldset>
   <fieldset class="border-t border-touch-border pt-7"><legend class="mb-2 font-display text-lg font-bold text-touch-dark">4. Photographs</legend><p class="text-sm text-touch-muted">Photographs can help us understand the condition, size and required work. Upload up to four JPG, PNG or WebP photographs. Maximum 3 MB per image.</p><input x-ref="photos" @change="updateFiles($event)" id="photos" name="photos[]" type="file" multiple accept="image/jpeg,image/png,image/webp" class="t2f-input mt-4"><ul class="mt-3 space-y-2" x-show="files.length"><template x-for="(file,index) in files" :key="file.name+index"><li class="flex items-center justify-between gap-3 text-sm"><span class="min-w-0 break-all" x-text="file.name"></span><button type="button" class="font-semibold text-touch-dark underline" @click="removeFile(index)" :aria-label="'Remove '+file.name">Remove</button></li></template></ul>@error('photos')<p class="form-error">{{ $message }}</p>@enderror @error('photos.*')<p class="form-error">{{ $message }}</p>@enderror</fieldset>
   <fieldset class="border-t border-touch-border pt-7"><legend class="mb-4 font-display text-lg font-bold text-touch-dark">5. Consent and Submission</legend><label class="flex items-start gap-3 text-sm leading-6"><input type="checkbox" name="consent" value="1" class="mt-1" @checked(old('consent'))><span>I agree that Touch2finish may use the information provided to review and respond to this enquiry. See the <a href="{{ route('legal.privacy') }}" class="font-semibold underline">Privacy Policy</a>. (required)</span></label>@error('consent')<p class="form-error">{{ $message }}</p>@enderror
  <button type="submit" class="btn-primary mt-6 w-full" :disabled="submitting" :aria-busy="submitting.toString()"><span x-show="!submitting">Send My Quote Request</span><span x-show="submitting" x-cloak>Submitting your request...</span></button></fieldset>
 </form>
</div>
