<?php

return [
    'business' => [
        'name' => 'Touch2finish',
        'tagline' => 'Clean. Move. Improve.',
        'phone_display' => '+44 7456 490 400',
        'phone_href' => '+447456490400',
        'whatsapp' => '447456490400',
        'email' => 'info@touch2finish.co.uk',
        'response_time' => 'Within 24 hours during normal working periods',
    ],

    'service_area' => [
        'primary' => 'London',
        'short_label' => 'London and surrounding locations',
        'summary' => 'Touch2finish primarily serves customers across London. Requests outside London may also be considered depending on the service, travel distance, job size and availability.',
    ],

    'services' => [
        'mobile-car-valeting' => [
            'slug' => 'mobile-car-valeting',
            'title' => 'Mobile Car Valeting',
            'short_title' => 'Valeting',
            'navigation_title' => 'Mobile Car Valeting',
            'eyebrow' => 'Vehicle Care at Your Location',
            'icon' => 'car-front',
            'hero_image' => 'images/services/mobile-car-valeting.webp',
            'thumbnail_image' => 'images/services/mobile-car-valeting.webp',
            'image_alt' => 'Representative mobile car valeting service at a customer location.',
            'image_position' => 'center',
            'summary' => 'Professional interior and exterior vehicle care delivered at your home, workplace or another agreed location.',
            'introduction' => [
                'Touch2finish provides mobile valeting for private cars, work vehicles, vans and selected business fleets.',
                'The required service should be based on the vehicle type, size, current condition, location and desired result. Customers should provide accurate details so the team can recommend the appropriate level of care.',
            ],
            'inclusions' => ['Interior vacuuming', 'Dashboard and trim cleaning', 'Internal glass cleaning', 'Exterior vehicle washing', 'Wheel and tyre cleaning', 'Mat cleaning', 'Selected upholstery cleaning', 'Selected leather cleaning and conditioning', 'Full interior and exterior valeting', 'Scheduled fleet-care support'],
            'inclusions_note' => 'The exact inclusions depend on the selected service and confirmed quotation.',
            'suitable_for' => ['Private vehicle owners', 'Work vehicles', 'Vans', 'Small business fleets', 'Selected dealership or commercial requirements'],
            'quote_requirements' => ['Vehicle make and model', 'Vehicle size', 'Current condition', 'Required service', 'Service postcode', 'Preferred date', 'Main areas of concern', 'Water availability', 'Electricity availability', 'Photographs where necessary'],
            'process' => ['Send the vehicle details', 'Confirm the location and requirements', 'Receive and approve the quotation', 'The agreed valeting service is completed and reviewed'],
            'faqs' => [
                ['question' => 'Do you come to my home or workplace?', 'answer' => 'Mobile services may be arranged at a suitable home, workplace or agreed location within the confirmed operating area.'],
                ['question' => 'Do you need access to water and electricity?', 'answer' => 'Requirements depend on the equipment and selected service. The team will confirm what is needed before the appointment.'],
                ['question' => 'Can you clean heavily soiled vehicles?', 'answer' => 'Customers should provide photographs before booking. Additional time, treatment or charges may be required depending on the condition.'],
                ['question' => 'What happens in bad weather?', 'answer' => 'Appointments may need to be adjusted where weather conditions prevent safe or effective completion.'],
                ['question' => 'Do you provide fleet valeting?', 'answer' => 'Scheduled or volume-based arrangements may be available for selected businesses, subject to location, vehicle numbers and availability.'],
            ],
            'related_services' => ['domestic-commercial-cleaning'],
            'cta_heading' => 'Ready to refresh your vehicle?',
            'cta_copy' => 'Send the vehicle details, service postcode and preferred date for a tailored quotation.',
            'seo_title' => 'Mobile Car Valeting | Touch2finish',
            'seo_description' => 'Request mobile interior and exterior car valeting from Touch2finish for private vehicles, work vehicles, vans and selected fleets.',
        ],

        'domestic-commercial-cleaning' => [
            'slug' => 'domestic-commercial-cleaning',
            'title' => 'Domestic and Commercial Cleaning',
            'short_title' => 'Cleaning',
            'navigation_title' => 'Domestic and Commercial Cleaning',
            'eyebrow' => 'Cleaning for Homes and Businesses',
            'icon' => 'sparkles',
            'hero_image' => 'images/services/domestic-commercial-cleaning.webp',
            'thumbnail_image' => 'images/services/domestic-commercial-cleaning.webp',
            'image_alt' => 'Representative domestic and commercial cleaning service in a modern property.',
            'image_position' => 'center',
            'summary' => 'Flexible cleaning services for homes, offices, rental properties and selected commercial spaces.',
            'introduction' => [
                'Touch2finish provides cleaning services based on the property type, size, condition and required result.',
                'Customers may request regular domestic cleaning, one-off cleaning, deep cleaning, move-in cleaning, end-of-tenancy cleaning or selected commercial arrangements.',
            ],
            'inclusions' => ['Regular domestic cleaning', 'One-off cleaning', 'Deep cleaning', 'Move-in cleaning', 'End-of-tenancy cleaning', 'Office cleaning', 'Commercial-space cleaning', 'Landlord property-turnaround cleaning', 'Post-refurbishment cleaning', 'Post-work cleaning'],
            'inclusions_note' => 'Specialist tasks and exact cleaning inclusions must be confirmed in the quotation.',
            'suitable_for' => ['Homeowners', 'Tenants', 'Landlords', 'Letting agents', 'Offices', 'Small businesses', 'Managed properties'],
            'quote_requirements' => ['Property postcode', 'Property type', 'Number of bedrooms', 'Number of bathrooms', 'Approximate property size', 'Required cleaning type', 'Current condition', 'Occupied or vacant status', 'Preferred date', 'Access information', 'Photographs where useful'],
            'process' => ['Describe the property and required cleaning', 'Share the property details and preferred date', 'Receive and approve the quotation', 'The agreed cleaning service is completed and reviewed'],
            'faqs' => [
                ['question' => 'Do you bring cleaning products and equipment?', 'answer' => 'This depends on the selected service. The quotation will explain what Touch2finish provides and whether any specialist products or equipment are charged separately.'],
                ['question' => 'Is oven cleaning automatically included?', 'answer' => 'Oven cleaning should only be considered included when it is specifically selected or confirmed in the quotation.'],
                ['question' => 'Do you offer end-of-tenancy cleaning?', 'answer' => 'End-of-tenancy cleaning may be provided based on the property size, condition, access and required checklist.'],
                ['question' => 'Can you guarantee the return of a tenancy deposit?', 'answer' => 'No cleaning company controls a landlord or agent’s deposit decision. Touch2finish can complete the agreed cleaning scope but should not guarantee deposit return.'],
                ['question' => 'Can commercial cleaning take place outside normal hours?', 'answer' => 'Alternative scheduling may be available for selected commercial clients, subject to confirmation.'],
            ],
            'related_services' => ['handyman-property-maintenance', 'refurbishment-decorating'],
            'cta_heading' => 'Tell us about the property.',
            'cta_copy' => 'Share the postcode, property size, current condition and required cleaning service.',
            'seo_title' => 'Domestic and Commercial Cleaning | Touch2finish',
            'seo_description' => 'Request domestic, deep, end-of-tenancy, office and selected commercial cleaning services from Touch2finish.',
        ],

        'removals-man-and-van' => [
            'slug' => 'removals-man-and-van',
            'title' => 'Removals (Man & Van)',
            'short_title' => 'Removals',
            'navigation_title' => 'Removals',
            'eyebrow' => 'Home, Office and Single-Item Moves',
            'icon' => 'truck',
            'hero_image' => 'images/services/removals-man-and-van.webp',
            'thumbnail_image' => 'images/services/removals-man-and-van.webp',
            'image_alt' => 'Representative removals team loading protected furniture into a van.',
            'image_position' => 'center',
            'summary' => 'Support for home moves, office relocations, furniture transport and individual-item collections.',
            'introduction' => [
                'Touch2finish helps customers organise selected moving and transportation requirements.',
                'The appropriate quotation should consider the collection location, destination, property access, item quantity, required vehicle, staffing and expected duration.',
            ],
            'inclusions' => ['House removals', 'Flat and apartment moves', 'Office relocation', 'Furniture transportation', 'Single-item collection and delivery', 'Man-and-van support', 'Internal furniture movement', 'Furniture dismantling where agreed', 'Furniture reassembly where agreed', 'Landlord and tenant moves'],
            'inclusions_note' => null,
            'suitable_for' => ['Homeowners', 'Tenants', 'Landlords', 'Offices', 'Small businesses', 'Furniture buyers and sellers'],
            'quote_requirements' => ['Collection postcode', 'Delivery postcode', 'Property type', 'Number of rooms', 'Floor level', 'Lift availability', 'Parking or access restrictions', 'Preferred moving date', 'Large or fragile items', 'Item inventory', 'Photographs where useful'],
            'process' => ['Send the collection and delivery details', 'Share the item, property and access information', 'Receive and approve the quotation', 'The agreed items are collected, transported and placed'],
            'faqs' => [
                ['question' => 'Do you move individual items?', 'answer' => 'Single-item collection and delivery may be available depending on the item size, location, access and schedule.'],
                ['question' => 'Can furniture be dismantled and reassembled?', 'answer' => 'Compatible dismantling or reassembly tasks may be included when they are agreed before the moving date.'],
                ['question' => 'Do you provide packing materials?', 'answer' => 'Available packing support and materials should be confirmed in the quotation.'],
                ['question' => 'How early should I book?', 'answer' => 'Customers should enquire as early as possible, especially for weekends, month-end dates or larger moves.'],
                ['question' => 'Are my belongings insured?', 'answer' => 'Applicable handling terms and responsibilities will be explained before the booking is confirmed.'],
            ],
            'related_services' => ['handyman-property-maintenance', 'domestic-commercial-cleaning'],
            'cta_heading' => 'Planning a move or collection?',
            'cta_copy' => 'Send the collection location, destination, item details and preferred date.',
            'seo_title' => 'Removals & Man and Van Services | Touch2finish',
            'seo_description' => 'Request house moves, office relocations, furniture transport and man-and-van support from Touch2finish.',
        ],

        'handyman-property-maintenance' => [
            'slug' => 'handyman-property-maintenance',
            'title' => 'Handyman and Property Maintenance',
            'short_title' => 'Handyman',
            'navigation_title' => 'Handyman and Property Maintenance',
            'eyebrow' => 'Practical Property Support',
            'icon' => 'hammer',
            'hero_image' => 'images/services/handyman-property-maintenance.webp',
            'thumbnail_image' => 'images/services/handyman-property-maintenance.webp',
            'image_alt' => 'Representative handyman assembling and installing household furniture.',
            'image_position' => 'center',
            'summary' => 'Assistance with furniture assembly, mounting, fittings, minor repairs and general property-maintenance tasks.',
            'introduction' => [
                'Touch2finish provides practical support for customers who have one task or a complete list of smaller property jobs.',
                'Customers should provide a full task list, property location and supporting photographs so the work can be reviewed before a quotation or appointment is confirmed.',
            ],
            'inclusions' => ['Flat-pack furniture assembly', 'Furniture dismantling', 'TV wall mounting', 'Shelf installation', 'Picture and mirror mounting', 'Curtain-pole installation', 'Blind fitting', 'Sealant replacement', 'Minor property repairs', 'Basic fixture installation', 'Landlord maintenance lists', 'Office furniture assembly'],
            'inclusions_note' => null,
            'safety_note' => 'Gas, electrical, structural and other regulated work should only be undertaken by appropriately qualified professionals. Such work must not be advertised or accepted unless the required qualification has been confirmed.',
            'suitable_for' => ['Homeowners', 'Tenants', 'Landlords', 'Letting agents', 'Offices', 'Managed properties'],
            'quote_requirements' => ['Property postcode', 'Complete task list', 'Number of tasks', 'Photographs', 'Materials already available', 'Access information', 'Parking information', 'Preferred date', 'Any urgency', 'Any specialist requirements'],
            'process' => ['Send one complete task list', 'Provide photographs and property information', 'Receive and approve the quotation', 'The agreed tasks are completed and reviewed'],
            'faqs' => [
                ['question' => 'Can I combine several small jobs?', 'answer' => 'Yes. Send one complete task list so the team can review the full requirement together.'],
                ['question' => 'Will you purchase materials?', 'answer' => 'Material supply must be agreed before the appointment and included separately in the quotation where applicable.'],
                ['question' => 'Do you complete electrical or gas work?', 'answer' => 'Only appropriately qualified professionals should undertake regulated work. Availability must be confirmed before booking.'],
                ['question' => 'Can handyman support be combined with removals?', 'answer' => 'Yes. Compatible tasks such as furniture dismantling or reassembly may be included in a coordinated quotation.'],
                ['question' => 'How is handyman work priced?', 'answer' => 'Pricing may depend on the task list, expected duration, materials, access, equipment and urgency. The quotation should explain the chosen pricing basis.'],
            ],
            'related_services' => ['removals-man-and-van', 'refurbishment-decorating'],
            'cta_heading' => 'Have a list of property jobs to complete?',
            'cta_copy' => 'Send the complete task list, property location and supporting photographs.',
            'seo_title' => 'Handyman and Property Maintenance | Touch2finish',
            'seo_description' => 'Request furniture assembly, mounting, fittings, minor repairs and property-maintenance support from Touch2finish.',
        ],

        'refurbishment-decorating' => [
            'slug' => 'refurbishment-decorating',
            'title' => 'Refurbishment and Decorating',
            'short_title' => 'Refurbishment',
            'navigation_title' => 'Refurbishment and Decorating',
            'eyebrow' => 'Refresh and Improve Your Property',
            'icon' => 'paint-roller',
            'hero_image' => 'images/services/refurbishment-decorating.webp',
            'thumbnail_image' => 'images/services/refurbishment-decorating.webp',
            'image_alt' => 'Representative interior decorating and property-refurbishment work.',
            'image_position' => 'center',
            'summary' => 'Selected painting, decorating, repair and property-improvement services for homes, rental properties and businesses.',
            'introduction' => [
                'Touch2finish supports customers who need to refresh or improve selected interior spaces.',
                'The quotation should consider the current surface condition, preparation requirements, desired finish, number of rooms, access and preferred schedule.',
            ],
            'inclusions' => ['Interior painting', 'Wall and ceiling preparation', 'Woodwork painting', 'Wallpaper installation', 'Wallpaper removal', 'Feature walls', 'Minor surface repairs', 'Rental-property refreshes', 'Move-in and move-out decorating', 'Office redecoration', 'Selected room refurbishment', 'Post-tenancy property improvements'],
            'inclusions_note' => null,
            'suitable_for' => ['Homeowners', 'Landlords', 'Letting agents', 'Tenants with permission', 'Offices', 'Small businesses', 'Managed properties'],
            'quote_requirements' => ['Property postcode', 'Number of rooms', 'Approximate room sizes', 'Current surface condition', 'Desired finish', 'Paint or wallpaper preference', 'Occupied or vacant status', 'Preferred completion date', 'Photographs', 'Repairs or preparation required'],
            'process' => ['Describe the space and intended result', 'Share room details, photographs and timing', 'Receive and approve the scope and quotation', 'The agreed preparation and decorative work is completed and reviewed'],
            'faqs' => [
                ['question' => 'Do you supply paint and materials?', 'answer' => 'Material supply should be explained and priced in the quotation.'],
                ['question' => 'Can you assist with colour selection?', 'answer' => 'Basic colour and finish guidance may be discussed as part of the project, subject to the service scope.'],
                ['question' => 'How long will the work take?', 'answer' => 'Duration depends on the room size, surface condition, preparation, drying time, selected finish and number of coats required.'],
                ['question' => 'Can decorating be combined with cleaning?', 'answer' => 'Yes. Post-work cleaning may be included as part of a coordinated requirement.'],
                ['question' => 'Do you provide full property development?', 'answer' => 'No. Touch2finish is presented on this website as providing selected decorating, repair, refurbishment and property-improvement services, not real-estate development.'],
            ],
            'related_services' => ['handyman-property-maintenance', 'domestic-commercial-cleaning'],
            'cta_heading' => 'Planning to refresh a property?',
            'cta_copy' => 'Send photographs, room details and a description of the result you want to achieve.',
            'seo_title' => 'Refurbishment and Decorating | Touch2finish',
            'seo_description' => 'Request interior painting, decorating, preparation, minor repairs and selected refurbishment services from Touch2finish.',
        ],
    ],

    'quote_form' => [
        'combined_slug' => 'combined-services',
        'combined_title' => 'Multiple or Combined Services',
        'preferred_contact_methods' => [
            'phone' => 'Phone call',
            'whatsapp' => 'WhatsApp',
            'email' => 'Email',
        ],
        'detail_fields' => [
            'mobile-car-valeting' => ['vehicle_make_model', 'vehicle_size', 'vehicle_condition', 'water_available', 'electricity_available'],
            'domestic-commercial-cleaning' => ['property_type', 'bedrooms', 'bathrooms', 'cleaning_type', 'occupancy_status'],
            'removals-man-and-van' => ['collection_postcode', 'delivery_postcode', 'property_size', 'floor_level', 'lift_available', 'moving_date', 'large_items'],
            'handyman-property-maintenance' => ['task_list', 'materials_available'],
            'refurbishment-decorating' => ['number_of_rooms', 'property_status', 'surface_condition', 'desired_finish'],
            'combined-services' => ['combined_services', 'combined_details'],
        ],
        'options' => [
            'vehicle_size' => ['small_car' => 'Small car', 'medium_car' => 'Medium car', 'large_car_suv' => 'Large car or SUV', 'van' => 'Van', 'other' => 'Other'],
            'vehicle_condition' => ['light' => 'Light cleaning required', 'moderate' => 'Moderate cleaning required', 'heavy' => 'Heavy cleaning required', 'not_sure' => 'Not sure'],
            'availability' => ['yes' => 'Yes', 'no' => 'No', 'not_sure' => 'Not sure'],
            'property_type' => ['house' => 'House', 'flat_apartment' => 'Flat or apartment', 'office' => 'Office', 'retail_commercial' => 'Retail or commercial space', 'communal_area' => 'Communal area', 'other' => 'Other'],
            'cleaning_type' => ['regular' => 'Regular cleaning', 'one_off' => 'One-off cleaning', 'deep' => 'Deep cleaning', 'move_in' => 'Move-in cleaning', 'end_of_tenancy' => 'End-of-tenancy cleaning', 'office_commercial' => 'Office or commercial cleaning', 'post_work' => 'Post-work cleaning', 'not_sure' => 'Not sure'],
            'occupancy_status' => ['occupied' => 'Occupied', 'vacant' => 'Vacant', 'partially_occupied' => 'Partially occupied', 'not_sure' => 'Not sure'],
            'property_size' => ['single_item' => 'Single item', 'room_small_load' => 'Room or small load', 'studio' => 'Studio', 'one_bedroom' => 'One-bedroom property', 'two_bedroom' => 'Two-bedroom property', 'three_bedroom' => 'Three-bedroom property', 'four_plus_bedrooms' => 'Four or more bedrooms', 'office_commercial' => 'Office or commercial move', 'other' => 'Other'],
            'lift_available' => ['yes' => 'Yes', 'no' => 'No', 'not_applicable' => 'Not applicable', 'not_sure' => 'Not sure'],
            'materials_available' => ['yes' => 'Yes', 'no' => 'No', 'some' => 'Some materials are available', 'not_sure' => 'Not sure'],
            'property_status' => ['occupied' => 'Occupied', 'vacant' => 'Vacant', 'partially_occupied' => 'Partially occupied', 'not_sure' => 'Not sure'],
            'surface_condition' => ['good' => 'Good condition', 'minor_preparation' => 'Minor preparation required', 'significant_preparation' => 'Significant preparation required', 'not_sure' => 'Not sure'],
        ],
    ],
    'quote_options' => [
        'multiple' => 'Multiple or Combined Services',
    ],

    'redirects' => [
        'car-valeting' => 'mobile-car-valeting',
        'cleaning' => 'domestic-commercial-cleaning',
        'removals-handyman' => 'removals-man-and-van',
        'interior-decor' => 'refurbishment-decorating',
        'real-estate' => null,
    ],
];
